{% set name = "nomade-hpc" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256 will be added after PyPI upload

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - nomade = nomade.cli:main

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=61.0
  run:
    - python >=3.9
    - click >=8.0
    - toml >=0.10
    - numpy >=1.21
    - pandas >=1.3
    - scipy >=1.7

test:
  imports:
    - nomade
  commands:
    - nomade --help

about:
  home: https://github.com/jtonini/nomade
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE
  summary: A lightweight HPC monitoring and predictive analytics tool
  description: |
    NOMADE (NOde MAnagement DEvice) is a lightweight, self-contained 
    monitoring and prediction system for HPC clusters. It uses ML-based
    job health prediction using similarity networks and provides
    actionable recommendations.
  dev_url: https://github.com/jtonini/nomade

extra:
  recipe-maintainers:
    - jtonini
